title: Eilish Bobicki RMT - Registered Massage Therapist in Boundary Area
email: eilishrmt@gmail.com
phone: "604-356-9517"

description: >-
  Eilish Bobicki RMT - Registered Massage Therapist serving the Boundary area in British Columbia. Professional therapeutic massage therapy, hot stone massage, and RMT functional facial massage. Book your appointment today for health and wellness treatments.

baseurl: ""
url: "https://eilishbobicki-rmt.ca"

author: Caleb Bobicki
logo: /assets/images/Logo.png

services:
  - name: "75 Minute Massage Therapy"
    duration: "75 min"
    price: "$145"
    description: "Includes assessment, treatment with hydrotherapy, and home care"

  - name: "75 Minute Hot Stone Massage"
    duration: "75 min"
    price: "$160"
    description: "Full relaxation with heated basalt stones"

  - name: "60 Minute Massage Therapy"
    duration: "60 min"
    price: "$125"
    description: "Includes assessment and targeted treatment"

  - name: "75 Minute RMT Functional Facial Massage"
    duration: "75 min"
    price: "$145"
    description: "Targets neck, shoulders, and scalp tension"
    note: "Please wait 3 weeks after filler/botox"

theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap


include: [".htaccess"]

defaults:
  - scope:
      path: "assets/Videos"
    values:
      video: true
  - scope:
      path: ""
    values:
      layout: "page"
  - scope:
      path: "_posts"
    values:
      layout: "post"
      author: "Eilish Bobicki"
      categories: ["Massage Therapy"]

webserver_headers:
  - "Content-Type: video/mp4"

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - .sass-cache/
  - .jekyll-cache/
  - README.md

keep_files:
  - ".well-known"

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge