# Site Settings
title: Eilish Bobicki RMT
email: eilishrmt@gmail.com  # Replace with your professional email
phone: "(555) 123-4567"        # Your business phone
address: 6376 19 Street, Grand Forks
  
  6376 19 Street, Grand Forks

description: >-
  Eilish Bobicki is a Registered Massage Therapist (RMT) recognized by the College of Registered Massage Therapy of British Columbia, serving the Boundary area with compassionate and therapeutic treatments. Specializing in therapeutic massage therapy, hot stone massage, and innovative RMT functional facial massage, Eilish provides personalized care to support your journey toward healing and enhanced well-being. With a focus on health and wellness, she offers comprehensive treatments including assessment, hydrotherapy, and customized home care plans. Whether you're seeking relief from chronic pain, stress reduction, or overall wellness maintenance, Eilish's professional expertise and caring approach help clients achieve optimal physical and mental health outcomes in a welcoming, therapeutic environment.

baseurl: ""  # Leave empty unless using GitHub project pages
url: "https://yourdomain.com"  # Replace with your actual domain


# Services
services:
  - name: "75 Minute Massage Therapy"
    duration: "75 min"
    price: "$145"
    description: "Includes assessment, treatment with hydrotherapy, and home care"

  - name: "75 Minute Hot Stone Massage"
    duration: "75 min"
    price: "$160"
    description: "Full relaxation with heated basalt stones"

  - name: "60 Minute Massage Therapy"
    duration: "60 min"
    price: "$125"
    description: "Includes assessment and targeted treatment"

  - name: "75 Minute RMT Functional Facial Massage"
    duration: "75 min"
    price: "$145"
    description: "Targets neck, shoulders, and scalp tension"
    note: "Please wait 3 weeks after filler/botox"

# Build Settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag  # Recommended for better SEO

include: [".htaccess"]
defaults:
  - scope:
      path: "assets/Videos"
    values:
      video: true

# Add proper MIME types
webserver_headers:
  - "Content-Type: video/mp4"

# Defaults (sets default front matter for different content types)
defaults:
  - scope:
      path: ""  # All files
    values:
      layout: "page"
  - scope:
      path: "_posts"  # Blog posts
    values:
      layout: "post"
      author: "Eilish Bobicki"

# Exclude files/folders from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - .sass-cache/
  - .jekyll-cache/
  - README.md

# Optional Performance Settings
keep_files:
  - ".well-known"  # For SSL verification etc.

# Markdown Processing
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge